# Ch24 - Very simple example: block obvious AI-generated junk / TODOs
import sys
from pathlib import Path

BLOCK_PATTERNS = [
    "TODO: implement later",
    "lorem ipsum",
    "Generated by Copilot",
]

def check_file(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return True
    lower = text.lower()
    return not any(pattern.lower() in lower for pattern in BLOCK_PATTERNS)

def main():
    failed = []
    for arg in sys.argv[1:]:
        p = Path(arg)
        if p.is_file() and not check_file(p):
            failed.append(str(p))
    if failed:
        print("❌ Vibe Governance: Blocked snowflake patterns in:")
        for f in failed:
            print(f" -", f)
        sys.exit(1)
    sys.exit(0)

if __name__ == "__main__":
    main()
