# Ch22 GitOps - Argo CD Application of Applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-pipelines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vibe-coding-platform/platform-starter.git
    targetRevision: main
    path: manifests/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
